CREATE FUNCTION GET_NR_CURSE_PARTICIPATE(pilot_id INT)
RETURNS INT
DETERMINISTIC
BEGIN
  DECLARE total INT;
  SELECT COUNT(*) INTO total
  FROM RezultatCursa
  WHERE PilotID = pilot_id;
  RETURN total;
END;