CREATE FUNCTION GET_MEDIE_PUNCTE(pilot_id INT)
RETURNS DECIMAL(5,2)
DETERMINISTIC
BEGIN
  DECLARE medie DECIMAL(5,2);
  SELECT AVG(Puncte) INTO medie
  FROM RezultatCursa
  WHERE PilotID = pilot_id;
  RETURN IFNULL(medie, 0);
END;